apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rabbitmq-admin
  namespace: rabbitmq-system
spec:
  ingressClassName: nginx
  rules:
    - host: "rabbitmq.192.168.0.1.nip.io"
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: rabbitmqcluster-prod
                port:
                  number: 156
  tls:
  - hosts:
    - "rabbitmq.192.168.0.1.nip.io"